"""baseline migration for starpay schema

Revision ID: e84daceb957b
Revises: 
Create Date: 2026-08-19 23:45:43.007198
"""

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
